$$$$$$$$\ $$\   $$\ $$$$$$$$\ $$$$$$$\  $$$$$$$$\ $$\      $$\ $$$$$$$$\       $$$$$$$$\ $$$$$$$\   $$$$$$\  $$\       $$\:
$$  _____|$$ |  $$ |\__$$  __|$$  __$$\ $$  _____|$$$\    $$$ |$$  _____|      \__$$  __|$$  __$$\ $$  __$$\ $$ |      $$ |:
$$ |      \$$\ $$  |   $$ |   $$ |  $$ |$$ |      $$$$\  $$$$ |$$ |               $$ |   $$ |  $$ |$$ /  $$ |$$ |      $$ |:
$$$$$\     \$$$$  /    $$ |   $$$$$$$  |$$$$$\    $$\$$\$$ $$ |$$$$$\             $$ |   $$$$$$$  |$$ |  $$ |$$ |      $$ |:
$$  __|    $$  $$<     $$ |   $$  __$$< $$  __|   $$ \$$$  $$ |$$  __|            $$ |   $$  __$$< $$ |  $$ |$$ |      $$ |:
$$ |      $$  /\$$\    $$ |   $$ |  $$ |$$ |      $$ |\$  /$$ |$$ |               $$ |   $$ |  $$ |$$ |  $$ |$$ |      $$ |:
$$$$$$$$\ $$ /  $$ |   $$ |   $$ |  $$ |$$$$$$$$\ $$ | \_/ $$ |$$$$$$$$\          $$ |   $$ |  $$ | $$$$$$  |$$$$$$$$\ $$$$$$$$\:
\________|\__|  \__|   \__|   \__|  \__|\________|\__|     \__|\________|         \__|   \__|  \__| \______/ \________|\________|:





# Made by Timp


# Thanks for purchasing my plugin. If you will have any suggestions, issues, Please join my discord or dm me on discord its really important for me to fix all the bugs.

# Discord - Timp#1303
# Discord-Server - https://discord.gg/FKfAkg2pNs